In [1]:
import geojson
import geopandas as gpd
import random

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.colors as colors

In [2]:
#Not needed at the moment
#dfs = pd.DataFrame({})

#for i in range(1,10):
#    df = pd.read_csv('./csv/sms-call-internet-mi-2013-11-0{}.csv'.format(i), parse_dates=['time'])
#    dfs = dfs.append(df)
#df = pd.read_csv('./csv/sms-call-internet-mi-2013-11-10.csv', parse_dates=['time'])
#dfs = dfs.append(df)
#dfs = dfs.fillna(0)

In [3]:
#dfgr = dfs[['cellid', 'time', 'smsin','smsout', 'callin','callout', 'internet']].groupby(['cellid'], as_index=True).sum()
#dfgr['hour'] = dfgr.time.dt.hour+dfgr.time.dt.minute/60+24*(dfgr.time.dt.day-1)
#dfgr = dfgr.set_index(['cell']).sort_index()
#dfgr.head()

In [4]:
cs_class = pd.DataFrame([], columns=["cellid", "lat", "lon", "smsin", "smsout","callin","callout","internet", "home", "high_dens","mid_dens","low_dens","work", "transport", "commercial", "commercial_low", "commercial_high", "offices", "touristic", "rural"])
#gdf = gpd.read_file('./geojsons/milano-grid.geojson')

with open("./geojsons/milano-grid.geojson") as json_file:
    json_data = geojson.load(json_file)

In [5]:
#Create a subset of the grids, and manually assign the labels according to the visual map

In [6]:
l=[]
#random.seed(23479589) #To make it reproducible
for i in range(4272,5272,100):
    #if (i-4272)<10
    for j in range(i,i+10):
        l.append(j)#
#print(l)

[4272, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4280, 4281, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4472, 4473, 4474, 4475, 4476, 4477, 4478, 4479, 4480, 4481, 4572, 4573, 4574, 4575, 4576, 4577, 4578, 4579, 4580, 4581, 4672, 4673, 4674, 4675, 4676, 4677, 4678, 4679, 4680, 4681, 4772, 4773, 4774, 4775, 4776, 4777, 4778, 4779, 4780, 4781, 4872, 4873, 4874, 4875, 4876, 4877, 4878, 4879, 4880, 4881, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 5072, 5073, 5074, 5075, 5076, 5077, 5078, 5079, 5080, 5081, 5172, 5173, 5174, 5175, 5176, 5177, 5178, 5179, 5180, 5181]

In [7]:
for i in l:
    tmp=pd.DataFrame([[json_data.features[i].properties["cellId"], np.mean(json_data.features[i].geometry.coordinates[0], axis=0)[1], np.mean(json_data.features[i].geometry.coordinates[0], axis=0)[0]]], columns=['cellid', 'lat', 'lon'])
    cs_class=cs_class.append(tmp)
    #print(np.mean(json_data.features[i].geometry.coordinates[0], axis=0))
    #print(json_data.features[i].properties["cellId"])
    json_data.features[i].properties = {
        "fill": colors.to_hex([ 1.0, 0.30, 0.1, 0.5 ], keep_alpha = True),
        "fill-opacity": 0.4,
        "stroke-width": 1,
        "stroke-opacity": 0.5,
        "cellId": i+1
    }

In [8]:
with open("./geojsons/test10by10.geojson", "w") as json_file:
    geojson.dump(json_data, json_file)

In [9]:
cs_class=cs_class.fillna(0)
cs_class = cs_class.set_index(['cellid']).sort_index()

cs_class.head()

,lat,lon,smsin,smsout,callin,callout,internet,home,high_dens,mid_dens,low_dens,work,transport,commercial,commercial_low,commercial_high,offices,touristic,rural
cellid,,,,,,,,,,,,,,,,,,,
4273,45.446569,9.229077,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4274,45.446563,9.232082,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4275,45.446557,9.235087,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4276,45.446550,9.238092,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4277,45.446544,9.241097,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [10]:
#cs_class.to_csv("./csv/classif10by10.csv")