In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score, cross_val_predict
#from sklearn.cluster import KMeans, OPTICS, AffinityPropagation

In [2]:
#Week 4-10 nov: smsin traffic
data = pd.read_csv("./classif/randomgrid/classif-randomgridweek_smsin.csv")
#data = pd.read_csv("./classif/10x10/classif10x10week_smsin.csv")
#data = pd.read_csv("./classif/20x20/classif20x20week_smsin.csv")

#data = pd.read_csv("./classif/randomgrid/classif-randomgridweekminute_smsin.csv")
#data = pd.read_csv("./classif/10x10/classif10x10weekminute_smsin.csv")
#data = pd.read_csv("./classif/20x20/classif20x20weekminute_smsin.csv")
data.head()

,Unnamed: 0,cellid,smsin0,smsin1,smsin2,smsin3,smsin4,smsin5,smsin6,smsin7,...,smsin159,smsin160,smsin161,smsin162,smsin163,smsin164,smsin165,smsin166,smsin167,h/w
0,0,5056,0.012011,0.004511,0.006024,0.001284,0.008181,0.009419,0.010504,0.061318,...,0.064753,0.086046,0.083524,0.092893,0.103237,0.085834,0.058215,0.074713,0.050449,1
1,1,5065,0.015551,0.016034,0.010442,0.001882,0.011099,0.006219,0.008772,0.032623,...,0.057131,0.063292,0.070518,0.074217,0.068301,0.062609,0.065101,0.047289,0.032491,1
2,2,5076,0.004295,0.000633,0.000654,0.000126,0.000022,0.000762,0.001013,0.005044,...,0.008667,0.011443,0.011025,0.014575,0.012598,0.011596,0.010492,0.006549,0.003338,1
3,3,5085,0.000532,0.000226,0.002825,0.000339,0.001135,0.000565,0.000758,0.004257,...,0.005713,0.008367,0.009751,0.006174,0.004943,0.007259,0.006518,0.006779,0.000949,1
4,4,5093,0.000565,0.000243,0.000000,0.000000,0.000244,0.000243,0.000000,0.000459,...,0.001241,0.000405,0.001727,0.001938,0.001135,0.003049,0.000028,0.000704,0.000702,1

In [3]:
y = data.iloc[:,170] #h/w
x = data.iloc[:,2:170] #smsin for the whole week (24x7)
#y = data.iloc[:,1010] #h/w
#x = data.iloc[:,2:1010] #smsin for the whole week (24x7)

In [4]:
### Clustering ###
#model = MeanShift()
#model = KMeans(n_clusters=2)
#model = OPTICS(min_samples=3)
#model = AffinityPropagation(random_state=5)
# fit model and predict clusters
#yhat=model.fit_predict(x)
# retrieve unique clusters
#clusters = np.unique(yhat)
#print(len(yhat))
###            ###

In [5]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [6]:
#y_pred = cross_val_predict(knn, x, y, cv=10)

In [7]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(), scores2.std()))

5 fold: 0.69 accuracy with a standard deviation of 0.05
10 fold: 0.685833 accuracy with a standard deviation of 0.070076

In [8]:
data = pd.read_csv("./classif/randomgrid/classif-randomgridweek_smsout.csv")
#data = pd.read_csv("./classif/10x10/classif10x10week_smsout.csv")
#data = pd.read_csv("./classif/20x20/classif20x20week_smsout.csv")

#data = pd.read_csv("./classif/randomgrid/classif-randomgridweekminute_smsout.csv")
#data = pd.read_csv("./classif/10x10/classif10x10weekminute_smsout.csv")
#data = pd.read_csv("./classif/20x20/classif20x20weekminute_smsout.csv")
data.head()

,Unnamed: 0,cellid,smsout0,smsout1,smsout2,smsout3,smsout4,smsout5,smsout6,smsout7,...,smsout159,smsout160,smsout161,smsout162,smsout163,smsout164,smsout165,smsout166,smsout167,h/w
0,0,5056,0.101734,0.071043,0.064414,0.059165,0.056025,0.065650,0.061833,0.117566,...,0.109311,0.111168,0.112425,0.126146,0.154156,0.141369,0.112037,0.122321,0.091537,1
1,1,5065,0.021726,0.029023,0.018900,0.008611,0.006542,0.010560,0.016914,0.050542,...,0.045295,0.048744,0.046317,0.072679,0.046186,0.040184,0.049990,0.052985,0.053980,1
2,2,5076,0.006605,0.001544,0.000899,0.000404,0.001280,0.000433,0.002126,0.004368,...,0.007004,0.003463,0.006186,0.010660,0.009756,0.008904,0.007875,0.007530,0.004022,1
3,3,5085,0.000635,0.000312,0.003905,0.001250,0.002031,0.000000,0.000472,0.003156,...,0.004334,0.006482,0.009256,0.003574,0.004783,0.005542,0.005455,0.002630,0.000791,1
4,4,5093,0.000116,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000260,...,0.001008,0.000857,0.002200,0.001193,0.002494,0.002609,0.000596,0.000000,0.000000,1

In [9]:
y = data.iloc[:,170] #h/w
x = data.iloc[:,2:170] #smsin for the whole week (24x7)
#y = data.iloc[:,1010] #h/w
#x = data.iloc[:,2:1010] #smsin for the whole week (24x7)

In [10]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [11]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(), scores2.std()))

5 fold: 0.72 accuracy with a standard deviation of 0.03
10 fold: 0.710167 accuracy with a standard deviation of 0.089593

In [12]:
data = pd.read_csv("./classif/randomgrid/classif-randomgridweek_callin.csv")
#data = pd.read_csv("./classif/10x10/classif10x10week_callin.csv")
#data = pd.read_csv("./classif/20x20/classif20x20week_callin.csv")

#data = pd.read_csv("./classif/randomgrid/classif-randomgridweekminute_callin.csv")
#data = pd.read_csv("./classif/10x10/classif10x10weekminute_callin.csv")
#data = pd.read_csv("./classif/20x20/classif20x20weekminute_callin.csv")
data.head()

,Unnamed: 0,cellid,callin0,callin1,callin2,callin3,callin4,callin5,callin6,callin7,...,callin159,callin160,callin161,callin162,callin163,callin164,callin165,callin166,callin167,h/w
0,0,5056,0.008915,0.006892,0.003664,0.000398,0.004511,0.004170,0.015551,0.056063,...,0.067714,0.060580,0.095011,0.120943,0.110621,0.066225,0.036686,0.045519,0.031220,1
1,1,5065,0.000592,0.002209,0.001151,0.000000,0.001722,0.004968,0.002596,0.030116,...,0.056429,0.049032,0.092697,0.087202,0.074335,0.066273,0.044606,0.028072,0.018426,1
2,2,5076,0.000160,0.000128,0.000454,0.000032,0.000519,0.000454,0.000486,0.006036,...,0.010266,0.011949,0.015749,0.015137,0.009967,0.010553,0.007238,0.004807,0.004581,1
3,3,5085,0.000012,0.000174,0.001245,0.000000,0.000174,0.000532,0.002501,0.003975,...,0.004979,0.006084,0.004351,0.005272,0.007209,0.005498,0.002228,0.002973,0.000898,1
4,4,5093,0.000043,0.000000,0.000043,0.000000,0.000000,0.000000,0.000043,0.001081,...,0.001208,0.002072,0.001912,0.001783,0.001531,0.002856,0.001409,0.002076,0.000663,1

In [13]:
y = data.iloc[:,170] #h/w
x = data.iloc[:,2:170] #smsin for the whole week (24x7)
#y = data.iloc[:,1010] #h/w
#x = data.iloc[:,2:1010] #smsin for the whole week (24x7)

In [14]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [15]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(), scores2.std()))

5 fold: 0.70 accuracy with a standard deviation of 0.06
10 fold: 0.714333 accuracy with a standard deviation of 0.070676

In [16]:
data = pd.read_csv("./classif/randomgrid/classif-randomgridweek_callout.csv")
#data = pd.read_csv("./classif/10x10/classif10x10week_callout.csv")
#data = pd.read_csv("./classif/20x20/classif20x20week_callout.csv")

#data = pd.read_csv("./classif/randomgrid/classif-randomgridweekminute_callout.csv")
#data = pd.read_csv("./classif/10x10/classif10x10weekminute_callout.csv")
#data = pd.read_csv("./classif/20x20/classif20x20weekminute_callout.csv")
data.head()

,Unnamed: 0,cellid,callout0,callout1,callout2,callout3,callout4,callout5,callout6,callout7,...,callout159,callout160,callout161,callout162,callout163,callout164,callout165,callout166,callout167,h/w
0,0,5056,0.011388,0.007216,0.003736,0.000000,0.000107,0.000089,0.015308,0.061990,...,0.051998,0.081521,0.104323,0.101359,0.116769,0.088041,0.039584,0.054108,0.016200,1
1,1,5065,0.013032,0.003555,0.000287,0.000209,0.002836,0.005350,0.010930,0.042503,...,0.057220,0.062897,0.097356,0.091580,0.102459,0.057665,0.055099,0.038631,0.025620,1
2,2,5076,0.004383,0.000249,0.000550,0.000032,0.000031,0.000186,0.002820,0.019741,...,0.013104,0.013892,0.026464,0.016832,0.016073,0.014494,0.011436,0.003498,0.000977,1
3,3,5085,0.000625,0.000506,0.000169,0.000338,0.000675,0.000172,0.000341,0.005252,...,0.006095,0.006626,0.007404,0.005637,0.005708,0.004760,0.004202,0.003038,0.001143,1
4,4,5093,0.000000,0.000363,0.000000,0.000000,0.000000,0.000000,0.000000,0.001049,...,0.000926,0.001049,0.000563,0.000323,0.000563,0.001448,0.001167,0.000604,0.000281,1

In [17]:
y = data.iloc[:,170] #h/w
x = data.iloc[:,2:170] #smsin for the whole week (24x7)
#y = data.iloc[:,1010] #h/w
#x = data.iloc[:,2:1010] #smsin for the whole week (24x7)

In [18]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

#y_pred = cross_val_predict(knn, x, y, cv=10)

In [19]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(), scores2.std()))

5 fold: 0.69 accuracy with a standard deviation of 0.04
10 fold: 0.685167 accuracy with a standard deviation of 0.052422

In [20]:
data = pd.read_csv("./classif/randomgrid/classif-randomgridweek_internet.csv")
#data = pd.read_csv("./classif/10x10/classif10x10week_internet.csv")
#data = pd.read_csv("./classif/20x20/classif20x20week_internet.csv")

#data = pd.read_csv("./classif/randomgrid/classif-randomgridweekminute_internet.csv")
#data = pd.read_csv("./classif/10x10/classif10x10weekminute_internet.csv")
#data = pd.read_csv("./classif/20x20/classif20x20weekminute_internet.csv")
data.head()

,Unnamed: 0,cellid,internet0,internet1,internet2,internet3,internet4,internet5,internet6,internet7,...,internet159,internet160,internet161,internet162,internet163,internet164,internet165,internet166,internet167,h/w
0,0,5056,0.084248,0.069885,0.063940,0.051539,0.049394,0.047676,0.060493,0.104546,...,0.132300,0.121041,0.122225,0.110215,0.133865,0.125480,0.106782,0.108380,0.097747,1
1,1,5065,0.043798,0.038791,0.032181,0.029329,0.026968,0.029614,0.031620,0.057980,...,0.068400,0.068772,0.072562,0.072472,0.065705,0.066591,0.064316,0.060162,0.057541,1
2,2,5076,0.006454,0.006126,0.006307,0.006273,0.006319,0.006829,0.008556,0.011719,...,0.010625,0.010742,0.010648,0.011286,0.012260,0.011456,0.009876,0.009497,0.008664,1
3,3,5085,0.004702,0.002743,0.002320,0.003885,0.001916,0.003082,0.005856,0.005418,...,0.009835,0.006834,0.011859,0.006173,0.009849,0.011938,0.014372,0.011942,0.007080,1
4,4,5093,0.001224,0.000614,0.000673,0.000700,0.000764,0.000706,0.001128,0.000664,...,0.002381,0.002431,0.001651,0.001195,0.001848,0.001191,0.002270,0.001331,0.001551,1

In [21]:
y = data.iloc[:,170] #h/w
x = data.iloc[:,2:170] #smsin for the whole week (24x7)
#y = data.iloc[:,1010] #h/w
#x = data.iloc[:,2:1010] #smsin for the whole week (24x7)

In [22]:
knn = KNeighborsClassifier(n_neighbors=10)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [23]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %f accuracy with a standard deviation of %f" % (scores2.mean(), scores2.std()))

5 fold: 0.67 accuracy with a standard deviation of 0.06
10 fold: 0.665333 accuracy with a standard deviation of 0.079878

In [24]:
#y_pred = cross_val_predict(knn, x, y, cv=10)
#print(y_pred)

In [25]:
#predicted = pd.DataFrame(np.transpose(y_pred),columns=['predicted'])
#predicted['cellid']=data2.cellid
#predicted.append(np.transpose(y_pred))
#predicted.head()

In [26]:
#predicted.to_csv('./csv/predicted_si20.csv')