In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.cluster import KMeans

In [2]:
#Train with 20x20 and random grid, test with full grid
#data = pd.read_csv("./classif/fullgrid/classifgridmon_callout.csv") #to predict
data = pd.read_csv("./classif/fullgrid/tn/classifgridmon_callout.csv")
#data2 = pd.read_csv("./classif/20x20/classif20x20_callout.csv") #daily
#data3 = pd.read_csv("./classif/randomgrid/classif-randomgrid_callout.csv") #daily
#data = pd.read_csv("./classif/20x20/classif20x20frid_callout.csv")
#data = pd.read_csv("./classif/20x20/classif20x20monminute_callout.csv")
data2 = pd.read_csv("./classif/20x20/tn/classif20x20mon_callout.csv") #daily

data2.head()
#20x20 grid, monday(4/11) - callout

,Unnamed: 0,cellid,callout0,callout1,callout2,callout3,callout4,callout5,callout6,callout7,...,callout15,callout16,callout17,callout18,callout19,callout20,callout21,callout22,callout23,hwr
0,0,3911,0.000462,0.000338,0.000139,0.000199,0.000139,0.000030,0.001039,0.008887,...,0.020608,0.026198,0.025946,0.017393,0.012738,0.010467,0.007428,0.002187,0.002705,1
1,1,3912,0.000508,0.000338,0.000000,0.000005,0.000000,0.000000,0.001217,0.007904,...,0.014863,0.020062,0.019671,0.017635,0.012003,0.009502,0.006503,0.001139,0.001081,1
2,2,3913,0.000307,0.000019,0.000068,0.000129,0.000068,0.000030,0.003456,0.010757,...,0.023277,0.029671,0.025969,0.031934,0.015540,0.012870,0.008423,0.003945,0.001572,2
3,3,3914,0.000449,0.000129,0.000085,0.000095,0.000060,0.000775,0.004408,0.010271,...,0.022930,0.026407,0.027359,0.023296,0.016112,0.011351,0.005754,0.002936,0.000987,2
4,4,3915,0.000164,0.000488,0.000644,0.000374,0.000015,0.000455,0.007449,0.007354,...,0.030748,0.027171,0.025362,0.023042,0.015630,0.010471,0.006392,0.003256,0.002061,2

In [3]:
y = data2.iloc[:,26] #h/w
#y = y.append(data3.iloc[:,26])

x = data2.iloc[:,2:26] #sms, calls, internet
#x = x.append(data3.iloc[:,2:26])

#y = data.iloc[:,146] #h/w
#x = data.iloc[:,2:146] #sms, calls, internet
x_test = data.iloc[:,2:26]

In [4]:
#x_test.head()
#y

In [5]:
#x

In [6]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(x,y)
scores1 = cross_val_score(knn, x, y, cv=5)
scores2 = cross_val_score(knn, x, y, cv=10)

In [7]:
print("5 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores1.mean(), scores1.std()))
print("10 fold: %0.2f accuracy with a standard deviation of %0.2f" % (scores2.mean(), scores2.std()))

5 fold: 0.47 accuracy with a standard deviation of 0.06
10 fold: 0.51 accuracy with a standard deviation of 0.05

In [8]:
y_predt = knn.predict(x_test) #predict h/w for all the grid (100x100)

model = KMeans(n_clusters=5)
#model = AffinityPropagation(random_state=5) - doesn't converge
yhat=model.fit_predict(x_test)

In [9]:
predicted = pd.DataFrame(np.transpose(y_predt),columns=['predicted'])
predicted['cellid'] = data.cellid
predicted.head()

   predicted  cellid
0          1    38.0
1          1  7471.0
2          1  7467.0
3          1  7465.0
4          1  7464.0

In [10]:
predicted.to_csv('./csv/pred_fullgrid_trento.csv')